openapi: 3.0.0
info:
  title: API Usuarios
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /api/usuario:
    get:
      summary: Obtener lista de usuarios
      tags:
        - Usuarios
      responses:
        "200":
          description: Lista de usuarios obtenida correctamente
        "404":
          description: No se encontraron usuarios
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre:
                      type: string
                    email:
                      type: string

  /api/usuario/nuevo:
    post:
      summary: Crear un nuevo usuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                email:
                  type: string
                password:
                  type: string
                rol:
                  type: string
      responses:
        "201":
          description: Usuario creado correctamente
        "500":
          description: Error en la petición
