openapi: 3.0.0
info:
  title: API de ejemplo
  description: Documentación mínima con Swagger
  version: "1.0.0"

paths:
  /hello:
    get:
      summary: Devuelve un saludo
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hola mundo!
